[tool.black]
line-length = 80
target-version = ['py39']
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | migrations
  | alembic
  | etc
  | venv
  | venv3.10
  | tgbot/scheme
)/
'''
